# Generated by Django 5.1.4 on 2024-12-30 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childId', models.IntegerField()),
                ('parentId', models.IntegerField()),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 9, 52, 55, 131629))),
                ('updated', models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 9, 52, 55, 131640))),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=500)),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 9, 52, 55, 118090))),
                ('updated', models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 9, 52, 55, 118114))),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
