# Generated by Django 5.1.4 on 2024-12-30 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenode',
            name='nodeId',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='nodemapping',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 12, 46, 11, 104655)),
        ),
        migrations.AlterField(
            model_name='nodemapping',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 12, 46, 11, 104663)),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 12, 46, 11, 104351)),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 30, 12, 46, 11, 104374)),
        ),
    ]
