# Generated by Django 5.1.4 on 2024-12-31 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemanager', '0002_treenode_nodeid_alter_nodemapping_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='nodeId',
        ),
        migrations.AlterField(
            model_name='nodemapping',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 17, 17, 19, 882986)),
        ),
        migrations.AlterField(
            model_name='nodemapping',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 17, 17, 19, 882996)),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 17, 17, 19, 882698)),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 17, 17, 19, 882719)),
        ),
    ]
